parameters:
#    vel_jo_user.example.class: VelJo\UserBundle\Example

services:
#    vel_jo_user.example:
#        class: %vel_jo_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
