_simple_main:
  pattern: /
  defaults:
      _controller: FrameworkBundle:Redirect:redirect
      route: _main
      permanent: true

_main:
      pattern: /{_locale}/
      defaults: {_controller: VelJoGHProjectBundle:Main:main}

_news:
      pattern: /{_locale}/news/
      defaults: {_controller: VelJoGHProjectBundle:Main:news}

_about:
      pattern: /{_locale}/about/
      defaults: {_controller: VelJoGHProjectBundle:Main:about}

_contact:
      pattern:  /{_locale}/contact/
      defaults: {_controller: VelJoGHProjectBundle:Main:contact}
            
#######################################################################################################################

_search:
        pattern: /{_locale}/search/
        defaults: {_controller: VelJoGHProjectBundle:Main:searchForm}

_search_band:
        pattern:  /{_locale}/search/{band}/
        defaults: {_controller: VelJoGHProjectBundle:Main:searchBandResult}

_search_band_album:
        pattern:  /{_locale}/search/{band}/{album}/
        defaults: {_controller: VelJoGHProjectBundle:Main:searchAlbumResult}

_search_band_album_song:
        pattern:  /{_locale}/search/{band}/{album}/{song}/
        defaults: {_controller: VelJoGHProjectBundle:Main:searchSongResult}
            
#######################################################################################################################

_comment:
        pattern:  /{_locale}/comment/
        defaults: {_controller: VelJoGHProjectBundle:Main:oneComment}
_single_comment:
        pattern:  /{_locale}/comment/{cid}
        defaults: {_controller: VelJoGHProjectBundle:Main:oneComment}
        options:
            expose: true
_post_success:
        pattern:  /{_locale}/success/
        defaults: {_controller: VelJoGHProjectBundle:Main:successAdd}
            
#######################################################################################################################

_article:
        pattern:  /{_locale}/article/
        defaults: {_controller: VelJoGHProjectBundle:Main:oneArticle}
_single_article:
        pattern:  /{_locale}/article/{aid}
        defaults: {_controller: VelJoGHProjectBundle:Main:oneArticle}
        options:
            expose: true
            
#######################################################################################################################

_category:
        pattern:  /{_locale}/category/
        defaults: {_controller: VelJoGHProjectBundle:Main:oneCategory}
_single_category:
        pattern:  /{_locale}/category/{catid}
        defaults: {_controller: VelJoGHProjectBundle:Main:oneCategory}
            
#######################################################################################################################

_tag:
        pattern:  /{_locale}/tag/
        defaults: {_controller: VelJoGHProjectBundle:Main:oneTag}
_single_tag:
        pattern:  /{_locale}/tag/{tid}
        defaults: {_controller: VelJoGHProjectBundle:Main:oneTag}
            
#######################################################################################################################

_gbook:
        pattern:  /{_locale}/gbook/
        defaults: {_controller: VelJoGHProjectBundle:Main:gbook}
        options:
            expose: true

#######################################################################################################################

_ajax_update_article_views:
        pattern:  /{_locale}/ajax/update/article_views/
        defaults: { _controller: VelJoGHProjectBundle:Ajax:ajaxUpdateArticleViews }
        options:
            expose: true
_load_more_article:
        pattern:  /{_locale}/ajax/load_articles/{page}/
        defaults: {_controller: VelJoGHProjectBundle:Ajax:ajaxLoadMoreArticle}
        options:
            expose: true