_main:
      pattern: /
      defaults: {_controller: VelJoGHProjectBundle:Main:main}

_news:
      pattern: /news/
      defaults: {_controller: VelJoGHProjectBundle:Main:news}

_about:
      pattern: /about/
      defaults: {_controller: VelJoGHProjectBundle:Main:about}

_contact:
      pattern: /contact/
      defaults: {_controller: VelJoGHProjectBundle:Main:contact}
            
#######################################################################################################################

_search:
        pattern: /search/
        defaults: {_controller: VelJoGHProjectBundle:Main:searchForm}

_search_band:
        pattern: /search/{bandName}/
        defaults: {_controller: VelJoGHProjectBundle:Main:searchBandResult}

_search_band_album:
        pattern: /search/{band}/{album}/
        defaults: {_controller: VelJoGHProjectBundle:Main:searchAlbumResult}

_search_band_album_song:
        pattern: /search/{band}/{album}/{song}/
        defaults: {_controller: VelJoGHProjectBundle:Main:searchSongResult}
            
#######################################################################################################################

_comment:
        pattern: /comment/
        defaults: {_controller: VelJoGHProjectBundle:Main:oneComment}
_single_comment:
        pattern: /comment/{cid}
        defaults: {_controller: VelJoGHProjectBundle:Main:oneComment}
        options:
            expose: true
_post_success:
        pattern: /success/
        defaults: {_controller: VelJoGHProjectBundle:Main:successAdd}
            
#######################################################################################################################

_article:
        pattern: /article/
        defaults: {_controller: VelJoGHProjectBundle:Main:oneArticle}
_single_article:
        pattern: /article/{aid}
        defaults: {_controller: VelJoGHProjectBundle:Main:oneArticle}
        options:
            expose: true
            
#######################################################################################################################

_category:
        pattern: /category/
        defaults: {_controller: VelJoGHProjectBundle:Main:oneCategory}
_single_category:
        pattern: /category/{catid}
        defaults: {_controller: VelJoGHProjectBundle:Main:oneCategory}
            
#######################################################################################################################

_tag:
        pattern: /tag/
        defaults: {_controller: VelJoGHProjectBundle:Main:oneTag}
_single_tag:
        pattern: /tag/{tid}
        defaults: {_controller: VelJoGHProjectBundle:Main:oneTag}
            
#######################################################################################################################

_gbook:
        pattern: /gbook/
        defaults: {_controller: VelJoGHProjectBundle:Main:gbook}
        options:
            expose: true

#######################################################################################################################

_ajax_update_article_views:
        pattern: /ajax/update/article_views/
        defaults: { _controller: VelJoGHProjectBundle:Ajax:ajaxUpdateArticleViews }
        options:
            expose: true
_load_more_article:
        pattern: /ajax/load_articles/{page}/
        defaults: {_controller: VelJoGHProjectBundle:Ajax:ajaxLoadMoreArticle}
        options:
            expose: true